#!/bin/zsh

#
# Copyright (c) Chris Jenkins 2019, 2020
#
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl
#

############################################################
# reset all shell options to default
emulate -LR zsh
# set required options
setopt nullglob
setopt shwordsplit
setopt ksharrays

############################################################
# reset PATH to system default
eval "$(/usr/libexec/path_helper)"

readonly -i mininterface=0
readonly -i maxinterface=20

integer activeOnly=1
integer retval=1

usage()
{
    echo
    echo "Usage:"
    echo
    echo "    getnwinterfaces { wifi | wired | tb | vpn | other | all } -active"
    echo
    echo "Displays the name of the machine's network interfaces of a given"
    echo "type (WiFi, Wired, Thunderbolt,  VPN, Other or all). Optionally"
    echo "limit the list to only those that are active."
    echo
    echo "Exits with a zero exit status if at least one interface was found"
    echo "or >0 otherwise."
    echo
    exit 100
}

isActive()
{
    declare -i ret=1
    declare ifname="$1"

    ifconfig "${ifname}" 2>/dev/null | grep -q 'status: active'
    ret=$?
    if [[ ${ret} -ne 0 ]] && \
       [[ ( "${ifname:0:4}" == "utun" ) || \
          ( "${ifname:0:3}" == "ppp" ) || \
          ( "${ifname:0:5}" == "ipsec" ) ]]
    then
        ifconfig "${ifname}" 2>/dev/null | grep -q '	inet '
        ret=$?
    fi

    return ${ret}
}

getWiFiInterfaces()
{
    local interfacebase="en"
    local interfacename=""
    local -i interfacenumber=${mininterface}
    local -i ret=1

    while [[ ${interfacenumber} -le ${maxinterface} ]]
    do
        interfacename="${interfacebase}${interfacenumber}"
        if networksetup -getairportpower "${interfacename}" >&/dev/null
        then
            if [[ ${activeOnly} -eq 1 ]]
            then
                echo "${interfacename}"
                ret=0
            elif isActive "${interfacename}"
            then
                echo "${interfacename}"
                ret=0
            fi
        fi
        interfacenumber=${interfacenumber}+1
    done

    return ${ret}
}

getOtherInterfaces()
{
    local interfacebase="en"
    local interfacename=""
    local -i interfacenumber=${mininterface}
    local -i ret=1

    while [[ ${interfacenumber} -le ${maxinterface} ]]
    do
        interfacename="${interfacebase}${interfacenumber}"
        if ifconfig "${interfacename}" >& /dev/null
        then
            if ! networksetup -getairportpower "${interfacename}" >&/dev/null
            then
                if networksetup -listnetworkserviceorder | grep '(Hardware ' | grep -ve 'Ethernet' -e 'LAN' -e 'Wi-Fi' -e 'L2TP' -e 'PPTP' | grep -qe "${interfacename})"
                then
                    if [[ ${activeOnly} -eq 1 ]]
                    then
                        echo "${interfacename}"
                        ret=0
                    elif isActive "${interfacename}"
                    then
                        echo "${interfacename}"
                        ret=0
                    fi
                fi
            fi
        fi
        interfacenumber=${interfacenumber}+1
    done

    return ${ret}
}

getWiredInterfaces()
{
    local interfacebase="en"
    local interfacename=""
    local -i interfacenumber=${mininterface}
    local -i ret=1

    while [[ ${interfacenumber} -le ${maxinterface} ]]
    do
        interfacename="${interfacebase}${interfacenumber}"
        if ifconfig "${interfacename}" >& /dev/null
        then
            if ! networksetup -getairportpower "${interfacename}" >&/dev/null
            then
                if networksetup -listnetworkserviceorder | grep -e 'Ethernet' -e 'LAN' | grep -qe "${interfacename})"
                then
                    if [[ ${activeOnly} -eq 1 ]]
                    then
                            echo "${interfacename}"
                            ret=0
                    elif isActive "${interfacename}"
                    then
                        echo "${interfacename}"
                        ret=0
                    fi
                fi
            fi
        fi
        interfacenumber=${interfacenumber}+1
    done

    return ${ret}
}

getTbInterfaces()
{
    local interfacebase="bridge"
    local interfacename=""
    local -i interfacenumber=${mininterface}
    local -i ret=1

    while [[ ${interfacenumber} -le ${maxinterface} ]]
    do
        interfacename="${interfacebase}${interfacenumber}"
        if ifconfig "${interfacename}" >& /dev/null
        then
            if ! networksetup -getairportpower "${interfacename}" >&/dev/null
            then
                if networksetup -listnetworkserviceorder | grep -e 'Thunderbolt Bridge' | grep -qe "${interfacename})"
                then
                    if [[ ${activeOnly} -eq 1 ]]
                    then
                            echo "${interfacename}"
                            ret=0
                    elif isActive "${interfacename}"
                    then
                        echo "${interfacename}"
                        ret=0
                    fi
                fi
            fi
        fi
        interfacenumber=${interfacenumber}+1
    done

    return ${ret}
}

getVpnInterfaces()
{
    local interfacebase1="utun"
    local interfacebase2="ppp"
    local interfacebase3="ipsec"
    local interfacename=""
    local -i interfacenumber=${mininterface}
    local -i ret=1

    while [[ ${interfacenumber} -le ${maxinterface} ]]
    do
        interfacename="${interfacebase1}${interfacenumber}"
        if ifconfig "${interfacename}" >& /dev/null
        then
            if [[ ${activeOnly} -eq 1 ]]
            then
                echo "${interfacename}"
                ret=0
            elif isActive "${interfacename}"
            then
                echo "${interfacename}"
                ret=0
            fi
        fi
        interfacename="${interfacebase2}${interfacenumber}"
        if ifconfig "${interfacename}" >& /dev/null
        then
            if [[ ${activeOnly} -eq 1 ]]
            then
                echo "${interfacename}"
                ret=0
            elif isActive "${interfacename}"
            then
                echo "${interfacename}"
                ret=0
            fi
        fi
        interfacename="${interfacebase3}${interfacenumber}"
        if ifconfig "${interfacename}" >& /dev/null
        then
            if [[ ${activeOnly} -eq 1 ]]
            then
                echo "${interfacename}"
                ret=0
            elif isActive "${interfacename}"
            then
                echo "${interfacename}"
                ret=0
            fi
        fi
        interfacenumber=${interfacenumber}+1
    done

    return ${ret}
}

if [[ $# -lt 1 ]] || [[ $# -gt 2 ]]
then
    usage
fi
if [[ $# -gt 1 ]]
then
    if [[ "$2" == "-active" ]]
    then
        activeOnly=0
    else
        usage
    fi
fi

case "$1" in
    wifi)
        getWiFiInterfaces
        retval=$?
        ;;
    wired)
        getWiredInterfaces
        retval=$?
        ;;
    tb)
        getTbInterfaces
        retval=$?
        ;;
    other)
        getOtherInterfaces
        retval=$?
        ;;
    vpn)
        getVpnInterfaces
        retval=$?
        ;;
    all)
        getWiFiInterfaces
        if [ $? -eq 0 ]
        then
            retval=0
        fi
        getWiredInterfaces
        if [ $? -eq 0 ]
        then
            retval=0
        fi
        getTbInterfaces
        if [ $? -eq 0 ]
        then
            retval=0
        fi
        getVpnInterfaces
        if [ $? -eq 0 ]
        then
            retval=0
        fi
        getOtherInterfaces
        if [ $? -eq 0 ]
        then
            retval=0
        fi
        ;;
    *)
        usage
        ;;
esac

exit ${retval}
